services:
  - type: web
    name: marcozero-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-por
      pip install -r requirements.txt
    startCommand: python -m backend.main
    envVars:
      - key: PORT
        value: 8000
