services:
  - type: web
    name: marcozero-backend
    env: python
    buildCommand: |
      set -e
      echo '==== Atualizando apt-get ===='
      apt-get update
      echo '==== Instalando Tesseract e idioma PT ===='
      apt-get install -y tesseract-ocr tesseract-ocr-por
      echo '==== Instalando dependências Python ===='
      pip install -r requirements.txt
      echo '==== Baixando modelo SpaCy pt_core_news_sm ===='
      python -m spacy download pt_core_news_sm
      echo '==== Verificando instalação do Tesseract ===='
      tesseract --version
      echo '==== Verificando modelo SpaCy ===='
      python -c "import spacy; spacy.load('pt_core_news_sm')"
    startCommand: python -m backend.main
    envVars:
      - key: PORT
        value: 8000
